# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener:  true
  service:
    view_handler: app.view_handler
  format_listener:
    enabled: true
    rules:
      - { path: ^/v1/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
  zone:
    - { path: ^/v1/* }
handcraftedinthealps_rest_routing:
  routing_loader:
    default_format: 'json'
    prefix_methods: true
    include_format: true
      # optional set supported formats else the configured one from fos_rest are used if installed:
      # formats:
      #     json: true
    #     xml: true

