parameters:
    env(CORS_ALLOW_ORIGIN): 'localhost'

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: true
        forced_allow_origin_value: ~
    paths:
        '^/v1/':
            allow_origin: ['*']
            allow_headers: ['Content-Type','Access-Control-Allow-Origin']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
        '^/auth/':
            allow_origin: ['*']
            allow_headers: ['Content-Type']
            allow_methods: [ 'OPTIONS','POST']
            max_age: 3600
