security:
  enable_authenticator_manager: true
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    App\Entity\User:
      algorithm: auto

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/v1/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      entry_point: App\Security\LoginFormAuthenticator
      custom_authenticators:
          - App\Security\LoginFormAuthenticator
          #- App\Security\FacebookAuthenticator
          #- App\Security\GoogleAuthenticator
      #            form_login:
      #                login_path: login
      #                check_path: login
      #                enable_csrf: true
      logout:
        path: app_logout
  access_control:
    - { path: ^/auth/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/statistique, roles: ROLE_ADMIN }
    - { path: ^/, roles: ROLE_ADMIN }
    - { path: ^/v1/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
